apiVersion: v1
kind: Service
metadata:
  name: my-devops-app
spec:
  selector:
    app: my-devops-app
  ports:
    - protocol: TCP
      port: 30000   # port of the service
      targetPort: 5000  # port of the container
  type: NodePort  # type of the service