name: CI pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/my-devops-app:latest
      - name: Update deployment.yaml
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/my-devops-app:${{ github.sha }}|" k8s/deployment.yaml
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          git add k8s/deployment.yaml
          git commit -m "update image tag to ${{ github.sha }}"
          git push origin master
